### ISSUE TITLE
FR Allow custom quality options without custom GStreamer pipeline

### ISSUE THREAD

**Issue by OffifialMITX** [EasyScreenCast/EasyScreenCast#142]
In the current state the most annoying thing for me is that I'm not allowed to record at 25 fps and I'd like to have the highest quality at that framerate.

I'm not sure how others think about it but the solution for me would be to just separate the framerate from other settings.

Also It's kinda pointless to show the audio encoding as a part of the settings since one can't change it. If there will be an option like that imo it should be separated as well.

**Comment by iacopodeenosee** [comment]
**The two parameters are linked and there is no point in separating them**, since there is a possibility to handle them separately; in the options window you can use 4 preset quality asset (GSP pipeline + FPS) if you want use something else just use a custom preset (custum GSP + custom FPS).
If you do not know how to build a GSP pipeline you can use one of the presets. How? read below

> How can i use a GSP pipeline preset with a custom FPS?

1. choose the preset quality you want
2. execute a screencast for few second
3. open a terminal
4. execute this command `journalctl --since=today --no-pager | grep "final GSP"`
5. paste the output into the custom GSP textbox
6. set your custom FPS
7. enjoy

> Also It's kinda pointless to show the audio encoding as a part of the settings since one can't change it. If there will be an option like that imo it should be separated as well.

It makes sense to let you know what kind of encoding you use, [however I wanted to implement the ability to change audio quality](https://github.com/EasyScreenCast/EasyScreenCast/issues/59), ** but I do not have time to build it, if you do it you are welcome.**
