### ISSUE TITLE
Improve filename template for the date and time format

### ISSUE THREAD

**Issue by larieu** [EasyScreenCast/EasyScreenCast#188]
feature request
I was not able to find in documentation if it is possible

now I have the saved file in format

Screencast_%d_%t
which generate something like
Screencast_12-30-2017_09:13:25 AM.webm
but I'll prefer to generate something like this

Screencast_20171230_091325.webm

( the general format )
Screencast_YYYYMMDD_HHmmss.webm
which is easier to save on a web server and create link to it automatically  (no spaces and special characters involved)

**Comment by gody01** [comment]
+1

**Comment by saltfishh** [comment]
yep,as the guy said,it's hard to select file which contains space in shell or terminal,hope more format

**Comment by adangel** [comment]
Currently the placeholders are replaced by gnome shell (https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/dbusServices/screencast/screencastService.js#L296 - method `_generateFilePath`).
However, we could prepare the full filename in ESC already, so that we have full control over the template.
